### ISSUE TITLE
Pictures for items as well as actors

### ISSUE THREAD

**Issue by apostate9** [lupestro/fvtt-fudge#3]
I'd like to use this system, but the inability to set a picture on an item is pretty... off-putting?
I don't want my inventory to be a series of white bags.
:-)

**Comment by lupestro** [comment]
Fair enough. I'll put it on the short list of soonest fixes. I suppose that means you want the picture to show up in the equipment list on the character sheet as well, no?

**Comment by lupestro** [comment]
I know a full-year-plus doesn't exactly apply as _soon_, but this tiny feature has finally arrived in 2.3.0 for Foundry 11 and 12.
